// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: censor/v1/censor.proto

package censor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	NewsId        string                 `protobuf:"bytes,2,opt,name=news_id,json=newsId,proto3" json:"news_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckCommentRequest) Reset() {
	*x = CheckCommentRequest{}
	mi := &file_censor_v1_censor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCommentRequest) ProtoMessage() {}

func (x *CheckCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_censor_v1_censor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCommentRequest.ProtoReflect.Descriptor instead.
func (*CheckCommentRequest) Descriptor() ([]byte, []int) {
	return file_censor_v1_censor_proto_rawDescGZIP(), []int{0}
}

func (x *CheckCommentRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CheckCommentRequest) GetNewsId() string {
	if x != nil {
		return x.NewsId
	}
	return ""
}

type CheckCommentResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Approved        bool                   `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`
	Reason          string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	FilteredComment string                 `protobuf:"bytes,3,opt,name=filteredComment,proto3" json:"filteredComment,omitempty"`
	Details         map[string]string      `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckCommentResponse) Reset() {
	*x = CheckCommentResponse{}
	mi := &file_censor_v1_censor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCommentResponse) ProtoMessage() {}

func (x *CheckCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_censor_v1_censor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCommentResponse.ProtoReflect.Descriptor instead.
func (*CheckCommentResponse) Descriptor() ([]byte, []int) {
	return file_censor_v1_censor_proto_rawDescGZIP(), []int{1}
}

func (x *CheckCommentResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *CheckCommentResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CheckCommentResponse) GetFilteredComment() string {
	if x != nil {
		return x.FilteredComment
	}
	return ""
}

func (x *CheckCommentResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_censor_v1_censor_proto protoreflect.FileDescriptor

const file_censor_v1_censor_proto_rawDesc = "" +
	"\n" +
	"\x16censor/v1/censor.proto\x12\tcensor.v1\"B\n" +
	"\x13CheckCommentRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x17\n" +
	"\anews_id\x18\x02 \x01(\tR\x06newsId\"\xf8\x01\n" +
	"\x14CheckCommentResponse\x12\x1a\n" +
	"\bapproved\x18\x01 \x01(\bR\bapproved\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12(\n" +
	"\x0ffilteredComment\x18\x03 \x01(\tR\x0ffilteredComment\x12F\n" +
	"\adetails\x18\x04 \x03(\v2,.censor.v1.CheckCommentResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012`\n" +
	"\rCensorService\x12O\n" +
	"\fCheckComment\x12\x1e.censor.v1.CheckCommentRequest\x1a\x1f.censor.v1.CheckCommentResponseB5Z3github.com/GoNewsProject/protonews/censor/v1;censorb\x06proto3"

var (
	file_censor_v1_censor_proto_rawDescOnce sync.Once
	file_censor_v1_censor_proto_rawDescData []byte
)

func file_censor_v1_censor_proto_rawDescGZIP() []byte {
	file_censor_v1_censor_proto_rawDescOnce.Do(func() {
		file_censor_v1_censor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_censor_v1_censor_proto_rawDesc), len(file_censor_v1_censor_proto_rawDesc)))
	})
	return file_censor_v1_censor_proto_rawDescData
}

var file_censor_v1_censor_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_censor_v1_censor_proto_goTypes = []any{
	(*CheckCommentRequest)(nil),  // 0: censor.v1.CheckCommentRequest
	(*CheckCommentResponse)(nil), // 1: censor.v1.CheckCommentResponse
	nil,                          // 2: censor.v1.CheckCommentResponse.DetailsEntry
}
var file_censor_v1_censor_proto_depIdxs = []int32{
	2, // 0: censor.v1.CheckCommentResponse.details:type_name -> censor.v1.CheckCommentResponse.DetailsEntry
	0, // 1: censor.v1.CensorService.CheckComment:input_type -> censor.v1.CheckCommentRequest
	1, // 2: censor.v1.CensorService.CheckComment:output_type -> censor.v1.CheckCommentResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_censor_v1_censor_proto_init() }
func file_censor_v1_censor_proto_init() {
	if File_censor_v1_censor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_censor_v1_censor_proto_rawDesc), len(file_censor_v1_censor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_censor_v1_censor_proto_goTypes,
		DependencyIndexes: file_censor_v1_censor_proto_depIdxs,
		MessageInfos:      file_censor_v1_censor_proto_msgTypes,
	}.Build()
	File_censor_v1_censor_proto = out.File
	file_censor_v1_censor_proto_goTypes = nil
	file_censor_v1_censor_proto_depIdxs = nil
}
