// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: censor/v1/censor.proto

package censor

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CensorService_CheckComment_FullMethodName = "/censor.v1.CensorService/CheckComment"
)

// CensorServiceClient is the client API for CensorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CensorServiceClient interface {
	CheckComment(ctx context.Context, in *CheckCommentRequest, opts ...grpc.CallOption) (*CheckCommentResponse, error)
}

type censorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCensorServiceClient(cc grpc.ClientConnInterface) CensorServiceClient {
	return &censorServiceClient{cc}
}

func (c *censorServiceClient) CheckComment(ctx context.Context, in *CheckCommentRequest, opts ...grpc.CallOption) (*CheckCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckCommentResponse)
	err := c.cc.Invoke(ctx, CensorService_CheckComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CensorServiceServer is the server API for CensorService service.
// All implementations must embed UnimplementedCensorServiceServer
// for forward compatibility.
type CensorServiceServer interface {
	CheckComment(context.Context, *CheckCommentRequest) (*CheckCommentResponse, error)
	mustEmbedUnimplementedCensorServiceServer()
}

// UnimplementedCensorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCensorServiceServer struct{}

func (UnimplementedCensorServiceServer) CheckComment(context.Context, *CheckCommentRequest) (*CheckCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckComment not implemented")
}
func (UnimplementedCensorServiceServer) mustEmbedUnimplementedCensorServiceServer() {}
func (UnimplementedCensorServiceServer) testEmbeddedByValue()                       {}

// UnsafeCensorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CensorServiceServer will
// result in compilation errors.
type UnsafeCensorServiceServer interface {
	mustEmbedUnimplementedCensorServiceServer()
}

func RegisterCensorServiceServer(s grpc.ServiceRegistrar, srv CensorServiceServer) {
	// If the following call pancis, it indicates UnimplementedCensorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CensorService_ServiceDesc, srv)
}

func _CensorService_CheckComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CensorServiceServer).CheckComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CensorService_CheckComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CensorServiceServer).CheckComment(ctx, req.(*CheckCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CensorService_ServiceDesc is the grpc.ServiceDesc for CensorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CensorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "censor.v1.CensorService",
	HandlerType: (*CensorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckComment",
			Handler:    _CensorService_CheckComment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "censor/v1/censor.proto",
}
